steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t us-east4-docker.pkg.dev/nest-tienda-microservices/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_MS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/nest-tienda-microservices/image-registry/orders-ms",
      ]
availableSecrets:
  secretManager:
    - versionName: projects/120878860277/secrets/DATABASE_URL/versions/1
      env: 'DATABASE_URL'
