steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t us-east1-docker.pkg.dev/nest-ms-tienda/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_MS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/nest-ms-tienda/image-registry/orders-ms",
      ]
availableSecrets:
  secretManager:
    - versionName: projects/600147795427/secrets/orders_database_url/versions/1
      env: 'DATABASE_URL'
options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
serviceAccount: 600147795427-compute@developer.gserviceaccount.com